name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  backend-build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Build & test (skip integration tests if any)
        run: mvn -B -DskipITs=true test package

  docker-build:
    runs-on: ubuntu-latest
    needs: backend-build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Optional: log in & push (set these secrets in your repo Settings → Secrets → Actions)
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./backend/Dockerfile
          push: false   # set to true if you configure DockerHub secrets
          tags: secureaccess/backend:ci-${{ github.sha }}
